### ISSUE TITLE
Provide of Paper for Free

### ISSUE THREAD

**Issue by kylhuk** [DataManagementLab/ScaleStore#1]
Hey there,

I stumbled upon this repo and I like the approach. To further understand it, I wanted to read the paper, but soon realized it was behind a paywall. Could you please publish your paper for everyone to read as part of this repo?

Thank you. 

--
kylhuk

**Comment by toziegler** [comment]
Hi, 

we hosted the paper on our university homepage: https://www.informatik.tu-darmstadt.de/media/systems/pdf_publications/ScaleStore_preprint.pdf
