### ISSUE TITLE
How to get the csvfiles?

### ISSUE THREAD

**Issue by LiYuTingxxn** [DataManagementLab/ScaleStore#2]
hello, I am interested in ScaleStore, which is a remarkable work. Could you please provide the csvfiles to run these executable files? Looking forward to your reply.

**Comment by toziegler** [comment]
Hi, 
thank you so much. 
I am assuming by _csvfiles_ you mean the experiment scripts? Those can be found in the `distexperiment/experiments` folder.  A detailed description on how the distexperiment runner is used can be found here https://github.com/mjasny/distexprunner. 
The build instructions are in the Readme: https://github.com/DataManagementLab/ScaleStore#cmake-build.

**Comment by LiYuTingxxn** [comment]
Thank you for your reply! 
Yes, the term "csvfiles" refers to the command specified by "numactl --membind=0 --cpunodebind=0 ./ycsb -ownIp=172.18.94.80 -nodes=1 -YCSB_all_workloads -worker=20  -csvFile=singlenode_oom_scalestore_ycsb_zipf.csv". This command uses the "-csvFile" option to specify a .csv file. Does this mean that the .csv file is generated by 'distexprunner'?

**Comment by toziegler** [comment]
It is generated by the executable `ycsb` -- the ycsb benchmark runner, so that is the file where the benchmark output is written to and you do not need to provide it beforehand.  And the name can be set by you to whatever you prefer.

**Comment by LiYuTingxxn** [comment]
OK，the .csv file is used to store the execution results, correct?
